### ISSUE TITLE
Website header

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#10]
[Designs](https://xd.adobe.com/view/67e9f444-0e3c-4693-5359-7e4a1c73b02e-11d8/screen/45b0f9cc-9dcc-4ce0-9157-86c4077b1a0c/Zea-Home-1920?fullscreen)
![image](https://user-images.githubusercontent.com/49651841/79377695-b37a3380-7f21-11ea-8685-3a0dd1b3b1ee.png)

https://zeainc.github.io/
![image](https://user-images.githubusercontent.com/49651841/79377606-92194780-7f21-11ea-8726-af64e77ad048.png)

## High Importance

- [ ] The header should remain fixed when you scroll up. See examples at [www.zea.live](www.zea.live) or [www.android.com](www.android.com). This is so that you don’t need to scroll to the top of the page to access the menu.
- [x] The header color is #BCBABC but it should be #393939.
- [ ] The menu text should highlight to show what page you are on. In the example below we are looking at the “About Zea” page.
![image](https://user-images.githubusercontent.com/49651841/79377813-e6242c00-7f21-11ea-866f-d44d97722a00.png)

## Medium Importance
- [ ] When you are at the top of the homepage it looks nicer if instead of a solid background that the header sits on top of a gradient shadow. You can see similar examples (without the shadow) at [www.zea.live](www.zea.live) and [www.android.com](www.android.com).
![image](https://user-images.githubusercontent.com/49651841/79377908-0a800880-7f22-11ea-853e-fe26519f3a9e.png)

## Low Importance
- [ ] The logo could be smaller so there is a larger vertical gap. The height on the header in the designs is also slightly higher at 80px.
![image](https://user-images.githubusercontent.com/49651841/79377986-28e60400-7f22-11ea-8ce9-db180c19f601.png)
- [x] The menu text could match the font size and color of the designs.

**Comment by juanvelazco** [comment]
All these changes have been made.
