### ISSUE TITLE
Website Video and Video Overlay

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#11]
[Designs](https://xd.adobe.com/view/67e9f444-0e3c-4693-5359-7e4a1c73b02e-11d8/screen/45b0f9cc-9dcc-4ce0-9157-86c4077b1a0c/Zea-Home-1920?fullscreen)
![image](https://user-images.githubusercontent.com/49651841/79378236-9a25b700-7f22-11ea-8efa-fe51d010f5af.png)

[https://zeainc.github.io/](https://zeainc.github.io/)
![image](https://user-images.githubusercontent.com/49651841/79378309-b6c1ef00-7f22-11ea-98fe-f84edf214c04.png)

## High Importance
- [x] @robhaines needs to finish the final video. The hero video can be found in [this folder](https://drive.google.com/drive/u/1/folders/1OVni02B_YH9U9nZ3Gqn6CNUDxQHc5IT7) called zea-hero.mp4
- [x] The subtitle should be formatted like this:
> Solve tough visualization problems in
> design, manufacturing, and construction
- [x] The "START HERE" button should scroll the page down to just below the video.
- [x] The "CONTACT US" button should scroll the page down the Contact Zea form.

## Medium Importance
- [ ] The text could use shadows and a gradient shadow background to make it stand out from the video. Overlaying a solid color over the video makes it look washed out.
- [x] Hover states on the buttons makes the desktop version seem more interactive.
![image](https://user-images.githubusercontent.com/49651841/79379246-3bf9d380-7f24-11ea-81f9-38fec32edca5.png)

## Low importance
- [x] If the text moved to the right it becomes more centered and you don't have to move your eyes to the far left to read it.
- [ ] There is an icon at the bottom of the video which scrolls the page down to just below the video. It's somewhat redundant as the "START HERE" button does the same thing.
![image](https://user-images.githubusercontent.com/49651841/79379743-fa1d5d00-7f24-11ea-9193-b6074417c354.png)

**Comment by robhaines** [comment]
1. The subtitle has been formatted differently, which is great. However, the title is now spread over three lines. We need it like this:
> **Powerful** browser-based
**3D** technology

![image](https://user-images.githubusercontent.com/49651841/79771607-a62fc100-82f4-11ea-8b20-08aeb6731e86.png)


2. The CONTACT US works great, but when you scroll down you can't see the top of the form:
![image](https://user-images.githubusercontent.com/49651841/79772937-5ce07100-82f6-11ea-8090-a04857fcf506.png)
It'd be better if we can see the top of the form instead.
![image](https://user-images.githubusercontent.com/49651841/79773084-97e2a480-82f6-11ea-8011-9cfb4af63f10.png)

**Comment by juanvelazco** [comment]
All these changes have been made. the contact Zea Title is still pending to be moved more to the left side.
