### ISSUE TITLE
Final Content - Videos and Images

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#20]
These are all the links to all the final content:

---------------

You can find all the homepage images and videos in [this folder](https://drive.google.com/drive/u/1/folders/1OVni02B_YH9U9nZ3Gqn6CNUDxQHc5IT7).

- [x] 1. zea-hero.webm
- [x] 2. hospital.webm
- [x] 3. graph.png - This image becomes too small to read on mobile. Is it possible to use a different image on mobile? One from [this folder](https://drive.google.com/drive/u/1/folders/1GTdoeBv_ysnDKQSrm9hG1z9apwpTbXpy)?
- [x] 4. collaboration.webm
- [x] 5. drive.png
- [x] 6. lidar.webm

![image](https://user-images.githubusercontent.com/49651841/79782154-3c1f1800-8304-11ea-8f2b-8ad6053d038b.png)

-----------------

The final text and all of the images for the "Meet the Team" section can be found in [this folder](https://drive.google.com/drive/u/1/folders/1DXrjy0KfHg-NAyDjqIGcxJevpZ5OUyQg).

![image](https://user-images.githubusercontent.com/49651841/79786508-2f51f280-830b-11ea-865f-a143f5155eb2.png)

**Comment by danieltaylor-nz** [comment]
all these changes are done

**Comment by robhaines** [comment]
These are looking good. I'll just create a new issue about the hospital video as the frame rate looks worse than I thought it would.
