### ISSUE TITLE
Photos should have a white circle around them when highlighted

### ISSUE THREAD

**Issue by danieltaylor-nz** [ZeaInc/zeainc.github.io#21]
Photos should have a white circle around them when highlighted
![image](https://user-images.githubusercontent.com/3458851/80252539-0dbf7680-863d-11ea-9883-815f3dc8b51e.png)

![image](https://user-images.githubusercontent.com/3458851/80252563-187a0b80-863d-11ea-9004-06ce8c2f638f.png)

**Comment by robhaines** [comment]
I had white borders on every photo as more of a visual thing. I was using the yellow name as the indicator that a person is selected.

It's the same idea I was using for the menu.
![image](https://user-images.githubusercontent.com/49651841/80608190-06f98080-89fc-11ea-9d84-57414bc7079f.png)

**Comment by robhaines** [comment]
We've decided to remove the borders. @danieltaylor-nz This issue can be closed but I don't have the option.
