### ISSUE TITLE
Title font consistency

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#22]
We have a few different font sizes and weights for titles at the moment. It'd be great if we could make the fonts, colors and positions the same across different pages.

![image](https://user-images.githubusercontent.com/49651841/80610560-1f1ecf00-89ff-11ea-969b-3e6ed2f3cf3a.png)

**Comment by robhaines** [comment]
Also on the Contact Zea form.

![image](https://user-images.githubusercontent.com/49651841/83046157-37890600-a00c-11ea-91d6-f2aae271413c.png)

**Comment by robhaines** [comment]
@elarcanista Just a couple more changes and this will be good enough.

![image](https://user-images.githubusercontent.com/49651841/85149051-76c70300-b216-11ea-9b0a-7f87c121e6e4.png)

![image](https://user-images.githubusercontent.com/49651841/85149185-9d853980-b216-11ea-99fd-9ae5264a5660.png)

**Comment by juanvelazco** [comment]
Changes are still pending.

**Comment by elarcanista** [comment]
This is solved in c621251
