### ISSUE TITLE
Contact form visual design - minor issues

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#27]
## Different font sizes

![image](https://user-images.githubusercontent.com/49651841/83045757-a154e000-a00b-11ea-8629-cf5b311675fd.png)

## Button stays on "MESSAGE SENT" state

After you submit a message it stays in the "MESSAGE SENT" state. This is very minor, but it could go back to the SEND MESSAGE after a couple of seconds.

![image](https://user-images.githubusercontent.com/49651841/83046054-0c061b80-a00c-11ea-8d49-a8d1682e8588.png)

**Comment by juanvelazco** [comment]
Changes are still pending.

**Comment by elarcanista** [comment]
This is solved in 58afd3e

**Comment by juanvelazco** [comment]
> This is solved in [58afd3e](https://github.com/ZeaInc/zeainc.github.io/commit/58afd3e1094fa842c895e8798db7e95af14ad67d)

Excellent.

![Contact form visual design - minor issues #27](https://user-images.githubusercontent.com/67337724/87787048-9f83ed80-c800-11ea-9021-1026d74d60cb.gif)
