### ISSUE TITLE
Button has box outline when clicked - minor issue

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#28]
Using Google Chrome on Window 10 the buttons have a box outline when you click them.

![image](https://user-images.githubusercontent.com/49651841/83047739-67d1a400-a00e-11ea-8dac-52ae5e602b7b.png)

Using Chrome on Android the box is yellow.

![image](https://user-images.githubusercontent.com/49651841/85034362-a1965600-b147-11ea-9c58-53c1e5d822fd.png)

**Comment by juanvelazco** [comment]
This is related to **Responsive - mobile buttons - minor issues #32** Changes are pending.

**Comment by elarcanista** [comment]
This is solved in 1b6dbbe

**Comment by juanvelazco** [comment]
> This is solved in [1b6dbbe](https://github.com/ZeaInc/zeainc.github.io/commit/1b6dbbe6f765591d26394e461c1f6e4bacced36c)

The box outline is fixed. Are you still working on the hamburger menu button? @elarcanista

**Comment by elarcanista** [comment]
The hamburger icon no longer has the box outline either. Or what are you referring to?

**Comment by juanvelazco** [comment]
> The hamburger icon no longer has the box outline either. Or what are you referring to?

@elarcanista about this one... Responsive - tapping the hamburger menu should close the menu #53

**Comment by elarcanista** [comment]
Yes, I can't figure that one out yet.

**Comment by juanvelazco** [comment]
This is fixed.
