### ISSUE TITLE
Add Froilan and Alvaro to Meet the Team

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#29]
We need photos and role descriptions for Froilan and Alvaro.

- [x] @robhaines can get the photos
- [ ] @danieltaylor-nz might have to help with the [descriptions](https://docs.google.com/document/d/1_f7zcqe9m3ynY_-j9WaCNLVj806dPWTH_2g8_Q_r1CA/edit#bookmark=id.nppmeru3mfo8)

**Comment by robhaines** [comment]
I've added photos to https://drive.google.com/drive/u/1/folders/1hnjVmvyHs7LzHn1sIDtzBgPgKmKTJOnc

![álvaro-pájaro-256x256](https://user-images.githubusercontent.com/49651841/83081455-57d5b680-a046-11ea-9b70-2d2f97cfc19c.png)

![froilan-moreno-256x256](https://user-images.githubusercontent.com/49651841/83081459-5a381080-a046-11ea-8388-ad1e2b913737.png)

**Comment by danieltaylor-nz** [comment]
this has been implemented
