### ISSUE TITLE
Responsive - hero text layout - minor issues

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#30]
# Mobile

This looks pretty good. I think there are just some line breaks in the middle of sentences that don't need to be there.

![image](https://user-images.githubusercontent.com/49651841/83072599-aaa67280-a034-11ea-95b6-1e817269ea0d.png)

![image](https://user-images.githubusercontent.com/49651841/83072515-834fa580-a034-11ea-8292-ce002cd4bf1d.png)

## Tablet

Looks good. Maybe just the line extending across the entire screen looks a bit odd.

![image](https://user-images.githubusercontent.com/49651841/83072734-e7726980-a034-11ea-996d-2474464b34b8.png)

**Comment by robhaines** [comment]
The layout seems to be broken at the moment as seen in #51. That probably needs to be fixed first.

**Comment by juanvelazco** [comment]
Changes are pending.

**Comment by elarcanista** [comment]
This was solved in 35cf167.
Unnecessary line breaks in the title were removed, the line no longer spans the entire screen.

**Comment by juanvelazco** [comment]
After reviewing all browsers, iPad, and android, I can confirm that this issue was fixed.
