### ISSUE TITLE
Responsive - header logo and hamburger icon - minor issues

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#31]
## Logo to the left

The logo is in the center and could probably be on the left.

## Hamburger icon moves

Normally the icon is here

![image](https://user-images.githubusercontent.com/49651841/83073101-7d0df900-a035-11ea-9f5e-a6653e0cdbaf.png)

But when you open the menu it jumps to the right a bit

![image](https://user-images.githubusercontent.com/49651841/83073179-9c0c8b00-a035-11ea-8b14-d8c0cadd5cf2.png)

In landscape mode the jump is more obvious. The menu is kind of cool but it's also causing weird placement of the hamburger menu. The [menu in the designs](https://xd.adobe.com/view/67e9f444-0e3c-4693-5359-7e4a1c73b02e-11d8/screen/b026a56b-2b8b-40ac-bf71-0c3da5afc459/Zea-Home-Mobile) would work in either view.

![image](https://user-images.githubusercontent.com/49651841/83073297-d24a0a80-a035-11ea-91d4-8dacff958d91.png)
![image](https://user-images.githubusercontent.com/49651841/83073343-e55cda80-a035-11ea-85fb-89e4100d0a21.png)

**Comment by juanvelazco** [comment]
This is related to **Responsive - tapping the hamburger menu should close the menu #53**
Changes are still pending.

**Comment by elarcanista** [comment]
This is solved in ef2f4c5

**Comment by juanvelazco** [comment]
> This is solved in [ef2f4c5](https://github.com/ZeaInc/zeainc.github.io/commit/ef2f4c5fd663f5cc8b1c9965a1652ffedaa4178b)

excellent.
