### ISSUE TITLE
Responsive - mobile buttons - minor issues

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#32]
This was tested with Google Chrome on Android.

- When you press a button it has a yellow outline
- It also looks like it changes to the hover state when it doesn't need to do that

![image](https://user-images.githubusercontent.com/49651841/83073971-f8bc7580-a036-11ea-9e72-3db52a328093.png)

Text fields also get the same yellow outline when you select them

![image](https://user-images.githubusercontent.com/49651841/83074075-2bff0480-a037-11ea-9b31-1116ee9b0f78.png)

**Comment by juanvelazco** [comment]
On Android, the text fields are not getting the yellow outline when you select them, however, the SEND MESSAGE button does.
@robhaines 

![Responsive - mobile buttons - minor issues #32](https://user-images.githubusercontent.com/67337724/87556373-2eb3c880-c67c-11ea-9473-dc690a6b212f.gif)

**Comment by robhaines** [comment]
@juanvelazco I think it's happening on http://zea.live/resources

On the dialog window that appears after you press the download button
![image](https://user-images.githubusercontent.com/49651841/87557393-7ab33d00-c67d-11ea-9928-1e926bd58b58.png)

**Comment by juanvelazco** [comment]
> @juanvelazco I think it's happening on http://zea.live/resources
> 
> On the dialog window that appears after you press the download button
> ![image](https://user-images.githubusercontent.com/49651841/87557393-7ab33d00-c67d-11ea-9928-1e926bd58b58.png)

Yes...

![Responsive - mobile buttons - minor issues 2 #32](https://user-images.githubusercontent.com/67337724/87559044-68d29980-c67f-11ea-83a0-e984c347a534.gif)

**Comment by elarcanista** [comment]
This is solved in 1b6dbbe. About the hover, should I disable it for mobile?

**Comment by juanvelazco** [comment]
> This is solved in [1b6dbbe](https://github.com/ZeaInc/zeainc.github.io/commit/1b6dbbe6f765591d26394e461c1f6e4bacced36c). About the hover, should I disable it for mobile?

@robhaines

**Comment by robhaines** [comment]
Yes, we don't need hover for touch events on mobile.

**Comment by juanvelazco** [comment]
> This is solved in [1b6dbbe](https://github.com/ZeaInc/zeainc.github.io/commit/1b6dbbe6f765591d26394e461c1f6e4bacced36c). About the hover, should I disable it for mobile?

Excellent.
