### ISSUE TITLE
Responsive - footer layout - minor issues

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#33]
The footer layout is a bit messy and a couple of the links are very close together.

![image](https://user-images.githubusercontent.com/49651841/83074263-7e402580-a037-11ea-9c7c-f48d569f43b6.png)

![image](https://user-images.githubusercontent.com/49651841/83074291-8730f700-a037-11ea-95e0-222d5ae60963.png)

On tablet the links are a bit squashed up.

![image](https://user-images.githubusercontent.com/49651841/83074447-cbbc9280-a037-11ea-8f21-3e5b03e442c7.png)

![image](https://user-images.githubusercontent.com/49651841/83074475-d9721800-a037-11ea-8ef3-d67391ae2f5f.png)

**Comment by juanvelazco** [comment]
This improvement is still pending

**Comment by juanvelazco** [comment]
This is fixed.
