### ISSUE TITLE
Responsive - resources layout - very minor tweaks

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#34]
On the resources page there are lines beneath the whitepaper thumbnails. They are using the wrong yellow. We only use #F9CE03 and then #FBE167 as a secondary hover color.

![image](https://user-images.githubusercontent.com/49651841/83074889-8e0c3980-a038-11ea-9444-79132ac77cf5.png)

Also on the first whitepaper there is a gap between the image and the line. On the second on there isn't.

![image](https://user-images.githubusercontent.com/49651841/83074728-471e4400-a038-11ea-8a7a-7cb189f11145.png)
![image](https://user-images.githubusercontent.com/49651841/83074753-51404280-a038-11ea-8dcf-ec42e6b77964.png)

**Comment by juanvelazco** [comment]
Perhaps this is already fixed? @robhaines 

![Responsive - resources layout - very minor tweaks #34](https://user-images.githubusercontent.com/67337724/87552444-505e8100-c677-11ea-850f-f96001c79af8.gif)

**Comment by robhaines** [comment]
@juanvelazco Yes, the color looks god.

Maybe you can close this issue and create a new one about the positioning of the line. It is a very minor issue but ...

On the first image there is a gap
![image](https://user-images.githubusercontent.com/49651841/87556816-bac5f000-c67c-11ea-8690-54e2e3be6a8a.png)

On the second there isn't
![image](https://user-images.githubusercontent.com/49651841/87556851-c6191b80-c67c-11ea-9faf-fa33b1cd531e.png)
