### ISSUE TITLE
Responsive - tablet layout

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#35]
I tested this by choosing iPad on while inspecting the site on my laptop on Google Chrome.

## Images are small
With the images on the left we have small images and a big gap.

![ipad-03](https://user-images.githubusercontent.com/49651841/83075221-18549d80-a039-11ea-8458-d2d511a8b81b.png)

![image](https://user-images.githubusercontent.com/49651841/83075256-286c7d00-a039-11ea-84b6-7e8fdb7c7667.png)

## Graph gets squashed
The graph image ([which also needs to be updated](https://drive.google.com/drive/u/1/folders/1OVni02B_YH9U9nZ3Gqn6CNUDxQHc5IT7)) get squashed and distorted.
![ipad-04](https://user-images.githubusercontent.com/49651841/83075438-78e3da80-a039-11ea-998f-5e05780404a8.png)

## Map and directions
![ipad-06](https://user-images.githubusercontent.com/49651841/83075533-a9c40f80-a039-11ea-842e-b9971a8268d2.png)
![image](https://user-images.githubusercontent.com/49651841/83075571-b6e0fe80-a039-11ea-94a2-53ac92bd26ee.png)

**Comment by juanvelazco** [comment]
This improvement is still pending.

![Responsive - tablet layout #35](https://user-images.githubusercontent.com/67337724/87551533-1e005400-c676-11ea-8ac2-2c42166d0681.gif)

**Comment by elarcanista** [comment]
In 8c8b75e videos now span all the way until the border of the screen so they look bigger now. Also for tablet maps are bigger and images/videos span the whole page as stated in the designs.

**Comment by juanvelazco** [comment]
> In [8c8b75e](https://github.com/ZeaInc/zeainc.github.io/commit/8c8b75e48308f83c4174eee25515405d262a84f7) videos now span all the way until the border of the screen so they look bigger now. Also for tablet maps are bigger and images/videos span the whole page as stated in the designs.

It looks super great now...

**Comment by juanvelazco** [comment]
All this was improved.
