### ISSUE TITLE
Bug - LinkedIn link doesn't take you to public page

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#36]
This one is weird. The "Follow Us" link in the footer takes you to https://www.linkedin.com/company/zea-inc which seems like the correct address.

![image](https://user-images.githubusercontent.com/49651841/83076307-ea705880-a03a-11ea-895a-9d9266e5a8d7.png)

But if you click the link LinkedIn wants you to sign up.

![image](https://user-images.githubusercontent.com/49651841/83076444-2c010380-a03b-11ea-9376-76f24ef0d837.png)

However if I just enter the link straight into an incognito window it takes me to the correct page.

![image](https://user-images.githubusercontent.com/49651841/83076537-5b177500-a03b-11ea-99bb-3c4d3394ff71.png)

**Comment by robhaines** [comment]
@danieltaylor-nz I tried this again and it was still acting weird.

**Comment by juanvelazco** [comment]
The first time, it never asked to log in.  @robhaines 

![Bug - LinkedIn link doesn't take you to public page #36](https://user-images.githubusercontent.com/67337724/87548683-733a6680-c672-11ea-8389-68893b3468dc.gif)


When I refreshed the page, it started asking me to log in.

![Bug - LinkedIn link doesn't take you to public page 2 #36](https://user-images.githubusercontent.com/67337724/87549621-a9c4b100-c673-11ea-9aee-aa22f323c370.gif)

**Comment by robhaines** [comment]
@juanvelazco We can close this issue.

I tried this with other websites and the same thing happens. It looks like it is an issue with LinkedIn.

It would be good to test what happens when you are logged in to a LinkedIn account. I am an admin of the Zea LinkedIn so I can't test it myself.
