### ISSUE TITLE
Bug - flicker after clicking "Resources" in the link

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#37]
Using Google Chrome Version 83.0.4103.61 (Official Build) (64-bit) on Window 10.

When I I click the "Resources" link the menu items and the scrollbar flicker after I move to the new page. It looks like the scrollbar is disappearing and reappearing super quick causing all the menu items to move.

![image](https://user-images.githubusercontent.com/49651841/83169178-3f15e100-a0d8-11ea-9f67-4e08133b92c9.png)

**Comment by elarcanista** [comment]
I wasn't able to replicate this. Is it still happening?

**Comment by juanvelazco** [comment]
@elarcanista is not happening to me on any browser. let's wait for @robhaines to test it on his own to confirm.

**Comment by robhaines** [comment]
This isn't happening anymore. We can close this one.

**Comment by juanvelazco** [comment]
This is fixed.
