### ISSUE TITLE
Link to MESH Consultants

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#38]
![image](https://user-images.githubusercontent.com/49651841/83169387-96b44c80-a0d8-11ea-86f3-809d240e35b7.png)

MESH Consultants can take us to https://www.meshconsultants.ca/

**Comment by danieltaylor-nz** [comment]
this is done

**Comment by robhaines** [comment]
The text has a style applied but doesn't seem to link anywhere.

**Comment by danieltaylor-nz** [comment]
strange... worked on localhost. Will review

**Comment by robhaines** [comment]
This is working now.
