### ISSUE TITLE
Implement new website designs for zea.live

### ISSUE THREAD

**Issue by danieltaylor-nz** [ZeaInc/zeainc.github.io#4]
Based on the mockups here: 
https://xd.adobe.com/view/67e9f444-0e3c-4693-5359-7e4a1c73b02e-11d8/screen/45b0f9cc-9dcc-4ce0-9157-86c4077b1a0c/Zea-Home-1920

**Comment by silvermiguel96** [comment]
Hi daniel, Please review the new zea.live and tell me what to improve. Thanks
