### ISSUE TITLE
Zahner quote layout

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#41]
I'd put the author after the quote and space things out a bit more. Speech marks around the quote would be good too.

![image](https://user-images.githubusercontent.com/49651841/83273978-c6278f80-a192-11ea-992d-0bc822fe29d9.png)

![image](https://user-images.githubusercontent.com/49651841/83274118-ed7e5c80-a192-11ea-90d3-0820f9a680d6.png)

**Comment by juanvelazco** [comment]
This improvement is still pending.

**Comment by elarcanista** [comment]
This was changed in e08f055

**Comment by juanvelazco** [comment]
This was reviewed and is complete.
