### ISSUE TITLE
Bug - black line on hero video

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#42]
![image](https://user-images.githubusercontent.com/49651841/83416369-2c582080-a3e6-11ea-9056-fd2485a568b9.png)

@robhaines will fix and upload a new video

**Comment by robhaines** [comment]
@danieltaylor-nz I've added a new version of zea-hero.mp4 to https://drive.google.com/drive/u/1/folders/1OVni02B_YH9U9nZ3Gqn6CNUDxQHc5IT7

**Comment by danieltaylor-nz** [comment]
i downloaded and committed the new video. It should be deployed shortly

**Comment by robhaines** [comment]
All fixed.

![image](https://user-images.githubusercontent.com/49651841/83460231-862f0980-a42b-11ea-87ac-2ebc0a57c17e.png)
