### ISSUE TITLE
Our team - responsive on small resize Chrome window - minor issue

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#43]
If you resize a the screen to a small size that is slightly bigger than a tablet the design breaks and you have to scroll up a lot to read the person's profile.

![image](https://user-images.githubusercontent.com/49651841/83417760-26633f00-a3e8-11ea-931e-c0389158d8cd.png)

I think we should switch to the tablet design after this stage, which is about 1000 pixels wide.

![image](https://user-images.githubusercontent.com/49651841/83417922-5ca0be80-a3e8-11ea-9832-9cdfdc3f581f.png)

**Comment by juanvelazco** [comment]
This improvement is still pending.

![Our team - responsive on small resize Chrome window - minor issue #43](https://user-images.githubusercontent.com/67337724/87547140-49804000-c670-11ea-99a9-079edb81c56b.gif)

**Comment by elarcanista** [comment]
The sizes at which the tablet designs kick in changed recently. Could you confirm this is still happening?

**Comment by juanvelazco** [comment]
> The sizes at which the tablet designs kick in changed recently. Could you confirm this is still happening?

In landscape mode looks great, now, I think @robhaines wanted to do the same on portrait mode?

**Comment by robhaines** [comment]
This is looking good to me. We can close this unless you find a situation where it's not working.
