### ISSUE TITLE
Meet the team - names spread over two lines

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#44]
A lot of the names are spread over two lines. It would be nice if most names are just on one line. If there's no room then we could use a smaller font.

For example:

**Daniel Taylor**

and not

**Daniel
Taylor**

![image](https://user-images.githubusercontent.com/49651841/83420400-33822d00-a3ec-11ea-9a9b-b1140eadb43a.png)

![image](https://user-images.githubusercontent.com/49651841/83421161-3f222380-a3ed-11ea-93d5-9f82b4349aee.png)

**Comment by juanvelazco** [comment]
This improvement is still pending.

**Comment by elarcanista** [comment]
Team members can now have longer names before the line break in fe1e389

**Comment by juanvelazco** [comment]
This improvement was applied correctly.
