### ISSUE TITLE
Scrollbars are different on different pages

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#45]
Because we changed the horizontal scrollbar on the About Zea page it also changed the normal vertical scrollbar.

This means that the scrollbar on that page is different from all the other pages.

![image](https://user-images.githubusercontent.com/49651841/83421363-958f6200-a3ed-11ea-8724-3d4f028ed31e.png)

**Comment by danieltaylor-nz** [comment]
we can move that CSS to a global stylesheet so they are the same everywhere.

**Comment by robhaines** [comment]
Looks good.
