### ISSUE TITLE
Industries on Hero Video

### ISSUE THREAD

**Issue by Michael-zea** [ZeaInc/zeainc.github.io#46]
Solve tough visualization problems in **design, manufacturing, and construction** should be **Architecture, Engineering, and Construction**

NOTE: it's often referred to as AEC
![image](https://user-images.githubusercontent.com/65655656/83509340-49016080-a499-11ea-9461-d7731316cb65.png)

**Comment by robhaines** [comment]
We can close this issue and leave it as it is. Maybe we can update it later, particularly as we improve the video.

**Comment by juanvelazco** [comment]
This improvement is pending.


![Industries on Hero Video #46](https://user-images.githubusercontent.com/67337724/87544196-a9c0b300-c66b-11ea-99d8-5bd8990a0fe8.gif)

**Comment by robhaines** [comment]
> This improvement is pending.

@juanvelazco This will stay the same. We can close this issue.
