### ISSUE TITLE
Video is not playing and text overlays visuals

### ISSUE THREAD

**Issue by danieltaylor-nz** [ZeaInc/zeainc.github.io#47]

**Comment by danieltaylor-nz** [comment]
![image](https://user-images.githubusercontent.com/3458851/84797991-0c1c8a00-afc0-11ea-82ab-0bb74cdf9ae4.png)

**Comment by danieltaylor-nz** [comment]
https://converterpoint.com/

**Comment by robhaines** [comment]
If you open the video in a new tab you will notice that it's also a bit bigger than we have on the site. I'm not sure if it's possible to have it at the full size or not.

On the site
![image](https://user-images.githubusercontent.com/49651841/84803714-fad77b80-afc7-11ea-916a-33aa3633fe4d.png)

When opened in a new tab
![image](https://user-images.githubusercontent.com/49651841/84803737-ff9c2f80-afc7-11ea-99d0-cad6859361c7.png)

Size in [designs](https://xd.adobe.com/view/67e9f444-0e3c-4693-5359-7e4a1c73b02e-11d8/screen/45b0f9cc-9dcc-4ce0-9157-86c4077b1a0c/Zea-Home-1920?fullscreen)
![image](https://user-images.githubusercontent.com/49651841/84804161-340feb80-afc8-11ea-8098-bc7dae4db0b6.png)

**Comment by juanvelazco** [comment]
This is fixed. Also related to **Video on Android mobile has a cast button it #54**

![Videos are small on a 1920x1080 desktop #55](https://user-images.githubusercontent.com/67337724/87477839-6d02a680-c5ee-11ea-9fb1-09ec459221d5.gif)
