### ISSUE TITLE
Contact us form is listed twice

### ISSUE THREAD

**Issue by danieltaylor-nz** [ZeaInc/zeainc.github.io#48]

**Comment by robhaines** [comment]
It also seems to be overlapping the footer on the "About Zea" page.

![image](https://user-images.githubusercontent.com/49651841/84800756-dbd6ea80-afc3-11ea-8ecc-4149283af2f8.png)

**Comment by robhaines** [comment]
✔ The extra contact us form has been removed
✔ The footer no longer overlaps on the "About Zea"

**Comment by juanvelazco** [comment]
It is fixed.

![ggg](https://user-images.githubusercontent.com/67337724/87477482-cf0edc00-c5ed-11ea-99ee-458070d27bd6.jpg)
