### ISSUE TITLE
Spelling "hudreds"

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#49]
hudreds = hundreds

![image](https://user-images.githubusercontent.com/49651841/84802940-e2b32c80-afc6-11ea-8881-037fd736b4a7.png)

**Comment by danieltaylor-nz** [comment]
this is done, should be deployed by now.

**Comment by juanvelazco** [comment]
It is fixed.

![índice](https://user-images.githubusercontent.com/67337724/87477179-514ad080-c5ed-11ea-9f58-4ffb0042922e.jpg)
