### ISSUE TITLE
Responsive - video is very large on mobile and text is too large

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#51]
A you can see the video seems to be full size on mobile an it is necessary to scroll down to see the bottom of it. It would be better if it just filled the height if the screen.

The text is also too large to fit on one screen. #30 is related to text layout and explains how the text could look

![Screenshot_20200618-091623](https://user-images.githubusercontent.com/49651841/85032012-f1275280-b144-11ea-8ce9-5348bd11eb3d.jpg)

![Screenshot_20200618-092202](https://user-images.githubusercontent.com/49651841/85032529-90e4e080-b145-11ea-993b-9d467b8a192b.jpg)

**Comment by elarcanista** [comment]
This was solved in 35cf167.
The video now fills the height of the screen for mobile. Text sizes were updated on mobile.

**Comment by juanvelazco** [comment]
after reviewing this on Android and iPhone, I can confirm that this issue was fixed. At least on my side.
