### ISSUE TITLE
Responsive - About Zea layout on mobile

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#52]
The layout seems to have moved around a bit. There's no need to make these exactly the same, just tidy.

# Meet the team
![Screenshot_20200618-092800](https://user-images.githubusercontent.com/49651841/85033265-621b3a00-b146-11ea-8ef8-29959524719a.jpg)

![image](https://user-images.githubusercontent.com/49651841/85033335-719a8300-b146-11ea-8694-105d3e862a3f.png)

# Visit us

![Screenshot_20200618-092807](https://user-images.githubusercontent.com/49651841/85033505-a4447b80-b146-11ea-8197-9c847efbc984.jpg)

![image](https://user-images.githubusercontent.com/49651841/85033534-adcde380-b146-11ea-8339-7f53801ed82b.png)

**Comment by elarcanista** [comment]
This layout was updated in dfc1629. Together with the changes in font sizes it should look much better now.

**Comment by juanvelazco** [comment]
> This layout was updated in [dfc1629](https://github.com/ZeaInc/zeainc.github.io/commit/dfc1629987b3dfe9d170e57b70a65a74de3b634c). Together with the changes in font sizes it should look much better now.

@elarcanista it is. This is fixed as well.
