### ISSUE TITLE
Responsive - tapping the hamburger menu should close the menu

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#53]
At the moment is seems to open and then close it again super fast.  It also has a yellow box outline as noted in #28

![image](https://user-images.githubusercontent.com/49651841/85034184-6bf16d00-b147-11ea-95a5-a0681bb84e17.png)

**Comment by juanvelazco** [comment]
The same thing happens on Android and iPad.

![Responsive - tapping the hamburger menu should close the menu #53](https://user-images.githubusercontent.com/67337724/87190390-fe54de80-c2b7-11ea-9e2a-bb2ba2926ee3.gif)

**Comment by juanvelazco** [comment]
Shouldn't this logo be moved more to the right side? @robhaines 

![ice_screenshot_20200714-082932](https://user-images.githubusercontent.com/67337724/87431460-491e7100-c5ac-11ea-95c4-62c37b7c9ef6.png)

**Comment by robhaines** [comment]
@juanvelazco Yes, you're right.

**Comment by elarcanista** [comment]
This is now fixed in 191fca7

**Comment by juanvelazco** [comment]
> This is now fixed in [191fca7](https://github.com/ZeaInc/zeainc.github.io/commit/191fca78365f4c25777b2fd2dfc884f380837d06)

Excellent.

**Comment by juanvelazco** [comment]
All this was fixed.
