### ISSUE TITLE
Videos are small on a 1920x1080 desktop

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#55]
It looks like the video is about 540 x 300 pixels on the site.

![image](https://user-images.githubusercontent.com/49651841/85035344-aa3b5c00-b148-11ea-8e21-b3abca177ec3.png)

The source files are 960 x 480
![image](https://user-images.githubusercontent.com/49651841/85035466-d525b000-b148-11ea-89ef-a0323e194285.png)

This is an example from [the designs](https://xd.adobe.com/view/67e9f444-0e3c-4693-5359-7e4a1c73b02e-11d8/screen/45b0f9cc-9dcc-4ce0-9157-86c4077b1a0c/Zea-Home-1920?fullscreen) with the full sized video.

![image](https://user-images.githubusercontent.com/49651841/85035635-04d4b800-b149-11ea-9b4f-85ade40f4697.png)

**Comment by juanvelazco** [comment]
Are these the correct dimensions now @robhaines ?

![Videos are small on a 1920x1080 desktop #55](https://user-images.githubusercontent.com/67337724/87319197-eca94c00-c4ee-11ea-8815-f5c1cecd9b0c.gif)

**Comment by robhaines** [comment]
This isn't a huge problem, but they still seem a bit small.

If you right click the videos and open them in a new tab you can compare the sizes in your browser. For example, you can play the same video in http://zea.live and http://zea.live/assets/collaboration.mp4

![image](https://user-images.githubusercontent.com/49651841/87321223-94277e00-c4f1-11ea-99c3-60deefeb49c2.png)

**Comment by juanvelazco** [comment]
Yeah, It seems bigger.

![Videos are small on a 1920x1080 desktop 2 #55](https://user-images.githubusercontent.com/67337724/87322736-67746600-c4f3-11ea-8439-a27060cbaff5.gif)

**Comment by elarcanista** [comment]
I updated the video sizes in 94743c7 so they roughly take up half the screen (like in the designs). Please inform me if those sizes are correct.

**Comment by juanvelazco** [comment]
> I updated the video sizes in [94743c7](https://github.com/ZeaInc/zeainc.github.io/commit/94743c753ae9bdf207ec069c871ecc26556c2ee6) so they roughly take up half the screen (like in the designs). Please inform me if those sizes are correct.

@robhaines

**Comment by robhaines** [comment]
Looks good.

**Comment by juanvelazco** [comment]
This is fixed.
