### ISSUE TITLE
Error when downloading white papers

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#57]
![image](https://user-images.githubusercontent.com/49651841/85176331-35971900-b23f-11ea-88ac-b7538db3d112.png)

- The PDFs open in new tabs correctly
- The "Download White Paper" dialog window stays open

**Comment by elarcanista** [comment]
This has already been solved in 6936390 and eac763a and is now working correctly

**Comment by juanvelazco** [comment]
it only gives the error when you enter an incorrect email. @robhaines @elarcanista 

![PDF download error](https://user-images.githubusercontent.com/67337724/86395126-5b6fe500-bc65-11ea-8a4e-b4b9d2943cde.gif)
