### ISSUE TITLE
Contact Zea title at the bottom

### ISSUE THREAD

**Issue by juanvelazco** [ZeaInc/zeainc.github.io#59]
I think the Contact Zea title should be moved more to the left. I don't know who I should be assigning these cases to. @danieltaylor-nz 

![ice_screenshot_20200623-140558](https://user-images.githubusercontent.com/67337724/85446959-b2393880-b55a-11ea-9a95-568149e1ea89.png)

**Comment by elarcanista** [comment]
This was solved in c621251a5123276d62990d9a6a89c8b155b9514c

**Comment by juanvelazco** [comment]
After reviewing on all browsers, I can cofirm that this issue was resolved.
