### ISSUE TITLE
Replace hospital video

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#65]
The hospital video's frame rate looks worse than I thought it would and should be replaced.

![image](https://user-images.githubusercontent.com/49651841/85571468-caac6000-b5f9-11ea-9eaf-fc1d202a1507.png)

**Comment by robhaines** [comment]
I added a new video called **hospital-alt.webm**. in [this folder](https://drive.google.com/drive/u/1/folders/1OVni02B_YH9U9nZ3Gqn6CNUDxQHc5IT7). I think that's good enough for now. We'll need someone with a powerful PC to record any new footage at 30 fps.

**Comment by juanvelazco** [comment]
On progress
