### ISSUE TITLE
Zea main website is not working on Safari.

### ISSUE THREAD

**Issue by juanvelazco** [ZeaInc/zeainc.github.io#66]
Zea's main website is not working on Safari when you open the browser on the Windows operating system.

Is not showing the Home, About Zea, and Resources menus.

its appearance is messy and is not showing the Zea logo.

![Zea main website not working on Safari](https://user-images.githubusercontent.com/67337724/86130198-6c73f700-baa9-11ea-9f0a-efbe9b31adc0.gif)

**Comment by juanvelazco** [comment]
The schedule viewer is not working at all.

![ice_screenshot_20200630-082712](https://user-images.githubusercontent.com/67337724/86131695-93cbc380-baab-11ea-8027-e3bbc44666dd.png)

**Comment by robhaines** [comment]
zea.live seemed to be displaying correctly for Diana on Safari. She just couldn't see the videos #67

**Comment by juanvelazco** [comment]
Zea main website is working on Safari now. This is being seen on Browserstack for Windows

![Videos are not displaying on Safari #67](https://user-images.githubusercontent.com/67337724/87154726-57545080-c27f-11ea-94d5-fa0ab93efd2b.gif)


The schedule viewer on Safari is working on Safari now. This is being seen on Browserstack for Windows


![Zea main website is working on Safari now  #66](https://user-images.githubusercontent.com/67337724/87155042-dea1c400-c27f-11ea-90bb-dbdad9a2e69d.gif)
