### ISSUE TITLE
Videos are not displaying on Safari

### ISSUE THREAD

**Issue by robhaines** [ZeaInc/zeainc.github.io#67]
Diana tested this and couldn't see any of the videos when using Safari.

![image](https://user-images.githubusercontent.com/49651841/86276333-5003b780-bb9a-11ea-9ade-df8c6077093a.png)

**Comment by elarcanista** [comment]
This was solved in 0cc582c

**Comment by juanvelazco** [comment]
Videos are displaying now on Safari.

![Videos are not displaying on Safari #67](https://user-images.githubusercontent.com/67337724/87153859-c16bf600-c27d-11ea-85fe-18af3b78488d.gif)
