### ISSUE TITLE
Zea.live website, all the text sections have double points

### ISSUE THREAD

**Issue by juanvelazco** [ZeaInc/zeainc.github.io#68]
![ice_screenshot_20200713-095925](https://user-images.githubusercontent.com/67337724/87319696-98529c00-c4ef-11ea-8793-0e66bcb3ab89.png)

![ice_screenshot_20200713-100142](https://user-images.githubusercontent.com/67337724/87319931-e4054580-c4ef-11ea-8ffe-0246fb108ddf.png)

![Videos are small on a 1920x1080 desktop #55](https://user-images.githubusercontent.com/67337724/87320002-f8494280-c4ef-11ea-8937-406987c1745b.gif)

**Comment by elarcanista** [comment]
This is solved in 0670c17

**Comment by juanvelazco** [comment]
> This is solved in [0670c17](https://github.com/ZeaInc/zeainc.github.io/commit/0670c17f5e809c1a17185d18ddf273d1c46de6af)

Exellent.
