### ISSUE TITLE
Zea.live website - About Zea, Maps look disorganized

### ISSUE THREAD

**Issue by juanvelazco** [ZeaInc/zeainc.github.io#69]
![ice_screenshot_20200714-084210](https://user-images.githubusercontent.com/67337724/87432678-efb74180-c5ad-11ea-916e-1b33712752b8.png)

This is what I would do. Just an idea.

![ice_screenshot_20200714-090800](https://user-images.githubusercontent.com/67337724/87435584-8df8d680-c5b1-11ea-805f-0a39480b1ccb.png)

**Comment by elarcanista** [comment]
The spacing for the maps was updated in 2f3beda. It better reflects the designs, the bottom and top spacing should look nicer now.

**Comment by juanvelazco** [comment]
> The spacing for the maps was updated in [2f3beda](https://github.com/ZeaInc/zeainc.github.io/commit/2f3bedabbfe2a084ab94d092e76d3ef763f210a1). It better reflects the designs, the bottom and top spacing should look nicer now.

It really does.. looks great.
