### ISSUE TITLE
Zea.live About Zea - Removing two integrants from "Meet the Team" section

### ISSUE THREAD

**Issue by juanvelazco** [ZeaInc/zeainc.github.io#71]
It is required this change.

![ice_screenshot_20200715-113706](https://user-images.githubusercontent.com/67337724/87571404-9cb5bb00-c68f-11ea-9c65-8925caabee3b.png)

**Comment by elarcanista** [comment]
Daniel and Katherine were removed in e5867a9

**Comment by juanvelazco** [comment]
This was applied correctly.
