### ISSUE TITLE
zea.live menu is on the left side instead of the right

### ISSUE THREAD

**Issue by juanvelazco** [ZeaInc/zeainc.github.io#72]
@dianaigl 
![ice_screenshot_20200721-114036](https://user-images.githubusercontent.com/67337724/88082372-52c54d00-cb47-11ea-9fee-6093276d882d.png)

**Comment by elarcanista** [comment]
This is changed in f56c81a

**Comment by juanvelazco** [comment]
> This is changed in [f56c81a](https://github.com/ZeaInc/zeainc.github.io/commit/f56c81af2873035a89485bc69f1ee9acca6aeaa1)

Excellent.

**Comment by juanvelazco** [comment]
This was fixed.
